# Generated by Django 6.0.4 on 2026-04-24 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='improvement_suggestions',
            field=models.JSONField(default=dict),
        ),
    ]
