# Generated by Django 5.2.7 on 2026-04-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillprogress',
            name='estimated_hours',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='skillprogress',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
